### ISSUE TITLE
Bug on Javascript export module :(

### ISSUE THREAD

**Issue by KGmajor** [YearOne-Prep/YearOne-prep-challenges#61]
We've got a linting error on our JavaScript file that looks like this. 

```
Run node javascript/add_challenge_to_spaces.js
/home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/javascript/js_actions.js:67
export {postQuestion}
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/javascript/add_challenge_to_spaces.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Error: Process completed with exit code 1.
```

🥺  Please take a look at the issue and fix the module exporting / importing error.

**Comment by machinesandpixels** [comment]
Hello, @KGmajor 

I'm trying to tackle this bug, however, I am encountering another bug in the process but not sure if its a bug. 

Steps, I've taken thus far. 

1) I replaced export {postQuestion} with module.exports = {postQuestion} in the js_actions.js file. 
2) I installed node-fetch and imported it into the js_actions.js file. 
    EX: const nodeFetch = require("node-fetch");

Now, this is the error I am getting after the above steps have been completed. 
  **error TypeError: Only absolute URLs are supported**

I went ahead and tried searching for a solution and it appears it's relating to environment variables and so I am not sure if this is actually a new bug or just an issue on my local machine. 

Please, let me know what to do from here.  Is this a new bug? Should I submit a pull request and have you check?
Not too sure what to do.

**Comment by KGmajor** [comment]
🤔  Thanks for taking a look at this @machinesandpixels! 

From what I'm seeing, the fetch here https://github.com/YearOne-Prep/YearOne-prep-challenges/blob/e5d9cf9b5a9b52349c356d44d83c494696149883/javascript/js_actions.js#L59  isn't formatted correctly. It's possible we need a different format like someone mentioned here https://github.com/node-fetch/node-fetch/issues/481#issuecomment-592491825.
