### ISSUE TITLE
Still an annoying bug in our JS files! 

### ISSUE THREAD

**Issue by KGmajor** [YearOne-Prep/YearOne-prep-challenges#66]
```
Run node javascript/add_challenge_to_spaces.js
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/node_modules/node-fetch/src/index.js from /home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/javascript/js_actions.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/node_modules/node-fetch/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/YearOne-prep-challenges/YearOne-prep-challenges/javascript/js_actions.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
Error: Process completed with exit code 1.

```

**Comment by jimmywarting** [comment]
https://github.com/YearOne-Prep/YearOne-prep-challenges/blob/920e2316a0ae144d390643cf0f5b8ccdd531c83f/.github/workflows/node.js.yml#L23

 run: npm install js-yaml node-fetch@2

**Comment by maiconm** [comment]
> https://github.com/YearOne-Prep/YearOne-prep-challenges/blob/920e2316a0ae144d390643cf0f5b8ccdd531c83f/.github/workflows/node.js.yml#L23
> 
> run: npm install js-yaml node-fetch@2

Did it work?
